/**
 * CivicSage
 * CivicSage is a service that allows you to index files and websites. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileSource model module.
 * @module model/FileSource
 * @version 0.4.0
 */
class FileSource {
    /**
     * Constructs a new <code>FileSource</code>.
     * @alias module:model/FileSource
     * @extends Object
     * @param fileId {String} The unique identifier for the indexed file
     * @param fileName {String} The name of the indexed file
     * @param title {String} The title of the indexed file, used in search results
     */
    constructor(fileId, fileName, title) { 
        
        FileSource.initialize(this, fileId, fileName, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fileId, fileName, title) { 
        obj['fileId'] = fileId;
        obj['fileName'] = fileName;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>FileSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FileSource} obj Optional instance to populate.
     * @return {module:model/FileSource} The populated <code>FileSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileSource();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('fileId')) {
                obj['fileId'] = ApiClient.convertToType(data['fileId'], 'String');
            }
            if (data.hasOwnProperty('fileName')) {
                obj['fileName'] = ApiClient.convertToType(data['fileName'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FileSource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FileSource</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FileSource.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['fileId'] && !(typeof data['fileId'] === 'string' || data['fileId'] instanceof String)) {
            throw new Error("Expected the field `fileId` to be a primitive type in the JSON string but got " + data['fileId']);
        }
        // ensure the json data is a string
        if (data['fileName'] && !(typeof data['fileName'] === 'string' || data['fileName'] instanceof String)) {
            throw new Error("Expected the field `fileName` to be a primitive type in the JSON string but got " + data['fileName']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

FileSource.RequiredProperties = ["fileId", "fileName", "title"];

/**
 * The unique identifier for the indexed file
 * @member {String} fileId
 */
FileSource.prototype['fileId'] = undefined;

/**
 * The name of the indexed file
 * @member {String} fileName
 */
FileSource.prototype['fileName'] = undefined;

/**
 * The title of the indexed file, used in search results
 * @member {String} title
 */
FileSource.prototype['title'] = undefined;






export default FileSource;

