/**
 * CivicSage
 * CivicSage is a service that allows you to index files and websites. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetMetadataKeys200Response model module.
 * @module model/GetMetadataKeys200Response
 * @version 0.4.0
 */
class GetMetadataKeys200Response {
    /**
     * Constructs a new <code>GetMetadataKeys200Response</code>.
     * @alias module:model/GetMetadataKeys200Response
     */
    constructor() { 
        
        GetMetadataKeys200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetMetadataKeys200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetMetadataKeys200Response} obj Optional instance to populate.
     * @return {module:model/GetMetadataKeys200Response} The populated <code>GetMetadataKeys200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetMetadataKeys200Response();

            if (data.hasOwnProperty('keys')) {
                obj['keys'] = ApiClient.convertToType(data['keys'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetMetadataKeys200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetMetadataKeys200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['keys'])) {
            throw new Error("Expected the field `keys` to be an array in the JSON data but got " + data['keys']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} keys
 */
GetMetadataKeys200Response.prototype['keys'] = undefined;






export default GetMetadataKeys200Response;

