/**
 * CivicSage
 * CivicSage is a service that allows you to index files and websites. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IndexWebsiteRequest model module.
 * @module model/IndexWebsiteRequest
 * @version 0.1.0
 */
class IndexWebsiteRequest {
    /**
     * Constructs a new <code>IndexWebsiteRequest</code>.
     * @alias module:model/IndexWebsiteRequest
     * @param url {String} The URL of the website to index
     */
    constructor(url) { 
        
        IndexWebsiteRequest.initialize(this, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url) { 
        obj['url'] = url;
    }

    /**
     * Constructs a <code>IndexWebsiteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IndexWebsiteRequest} obj Optional instance to populate.
     * @return {module:model/IndexWebsiteRequest} The populated <code>IndexWebsiteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IndexWebsiteRequest();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('additionalMetadata')) {
                obj['additionalMetadata'] = ApiClient.convertToType(data['additionalMetadata'], {'String': 'String'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IndexWebsiteRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IndexWebsiteRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IndexWebsiteRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}

IndexWebsiteRequest.RequiredProperties = ["url"];

/**
 * The URL of the website to index
 * @member {String} url
 */
IndexWebsiteRequest.prototype['url'] = undefined;

/**
 * @member {Object.<String, String>} additionalMetadata
 */
IndexWebsiteRequest.prototype['additionalMetadata'] = undefined;






export default IndexWebsiteRequest;

