/**
 * CivicSage
 * CivicSage is a service that allows you to index files and websites. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SummarizeEmbeddingsRequest model module.
 * @module model/SummarizeEmbeddingsRequest
 * @version 0.2.0
 */
class SummarizeEmbeddingsRequest {
    /**
     * Constructs a new <code>SummarizeEmbeddingsRequest</code>.
     * @alias module:model/SummarizeEmbeddingsRequest
     * @param documentIds {Array.<String>} Ids of the documents to summarize
     * @param prompt {String} The prompt to use for summarizing the embeddings
     */
    constructor(documentIds, prompt) { 
        
        SummarizeEmbeddingsRequest.initialize(this, documentIds, prompt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentIds, prompt) { 
        obj['documentIds'] = documentIds;
        obj['prompt'] = prompt;
    }

    /**
     * Constructs a <code>SummarizeEmbeddingsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SummarizeEmbeddingsRequest} obj Optional instance to populate.
     * @return {module:model/SummarizeEmbeddingsRequest} The populated <code>SummarizeEmbeddingsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SummarizeEmbeddingsRequest();

            if (data.hasOwnProperty('documentIds')) {
                obj['documentIds'] = ApiClient.convertToType(data['documentIds'], ['String']);
            }
            if (data.hasOwnProperty('prompt')) {
                obj['prompt'] = ApiClient.convertToType(data['prompt'], 'String');
            }
            if (data.hasOwnProperty('systemPrompt')) {
                obj['systemPrompt'] = ApiClient.convertToType(data['systemPrompt'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SummarizeEmbeddingsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SummarizeEmbeddingsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SummarizeEmbeddingsRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['documentIds'])) {
            throw new Error("Expected the field `documentIds` to be an array in the JSON data but got " + data['documentIds']);
        }
        // ensure the json data is a string
        if (data['prompt'] && !(typeof data['prompt'] === 'string' || data['prompt'] instanceof String)) {
            throw new Error("Expected the field `prompt` to be a primitive type in the JSON string but got " + data['prompt']);
        }
        // ensure the json data is a string
        if (data['systemPrompt'] && !(typeof data['systemPrompt'] === 'string' || data['systemPrompt'] instanceof String)) {
            throw new Error("Expected the field `systemPrompt` to be a primitive type in the JSON string but got " + data['systemPrompt']);
        }

        return true;
    }


}

SummarizeEmbeddingsRequest.RequiredProperties = ["documentIds", "prompt"];

/**
 * Ids of the documents to summarize
 * @member {Array.<String>} documentIds
 */
SummarizeEmbeddingsRequest.prototype['documentIds'] = undefined;

/**
 * The prompt to use for summarizing the embeddings
 * @member {String} prompt
 */
SummarizeEmbeddingsRequest.prototype['prompt'] = undefined;

/**
 * The system prompt
 * @member {String} systemPrompt
 */
SummarizeEmbeddingsRequest.prototype['systemPrompt'] = undefined;






export default SummarizeEmbeddingsRequest;

