/**
 * CivicSage
 * CivicSage is a service that allows you to index files and websites. 
 *
 * The version of the OpenAPI document: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateIndexedWebsiteRequest model module.
 * @module model/UpdateIndexedWebsiteRequest
 * @version 0.6.1
 */
class UpdateIndexedWebsiteRequest {
    /**
     * Constructs a new <code>UpdateIndexedWebsiteRequest</code>.
     * @alias module:model/UpdateIndexedWebsiteRequest
     */
    constructor() { 
        
        UpdateIndexedWebsiteRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateIndexedWebsiteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateIndexedWebsiteRequest} obj Optional instance to populate.
     * @return {module:model/UpdateIndexedWebsiteRequest} The populated <code>UpdateIndexedWebsiteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateIndexedWebsiteRequest();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateIndexedWebsiteRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateIndexedWebsiteRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['ids'])) {
            throw new Error("Expected the field `ids` to be an array in the JSON data but got " + data['ids']);
        }

        return true;
    }


}



/**
 * An array of identifiers for the sources to update. This must only include and websiteIds. 
 * @member {Array.<String>} ids
 */
UpdateIndexedWebsiteRequest.prototype['ids'] = undefined;






export default UpdateIndexedWebsiteRequest;

