/**
 * CivicSage
 * CivicSage is a service that allows you to index files and websites. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WebsiteSource model module.
 * @module model/WebsiteSource
 * @version 0.4.0
 */
class WebsiteSource {
    /**
     * Constructs a new <code>WebsiteSource</code>.
     * @alias module:model/WebsiteSource
     * @extends Object
     * @param websiteId {String} The unique identifier for the indexed website
     * @param url {String} The URL of the indexed website
     * @param title {String} The name of the indexed website
     */
    constructor(websiteId, url, title) { 
        
        WebsiteSource.initialize(this, websiteId, url, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, websiteId, url, title) { 
        obj['websiteId'] = websiteId;
        obj['url'] = url;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>WebsiteSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebsiteSource} obj Optional instance to populate.
     * @return {module:model/WebsiteSource} The populated <code>WebsiteSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebsiteSource();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('websiteId')) {
                obj['websiteId'] = ApiClient.convertToType(data['websiteId'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebsiteSource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebsiteSource</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebsiteSource.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['websiteId'] && !(typeof data['websiteId'] === 'string' || data['websiteId'] instanceof String)) {
            throw new Error("Expected the field `websiteId` to be a primitive type in the JSON string but got " + data['websiteId']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

WebsiteSource.RequiredProperties = ["websiteId", "url", "title"];

/**
 * The unique identifier for the indexed website
 * @member {String} websiteId
 */
WebsiteSource.prototype['websiteId'] = undefined;

/**
 * The URL of the indexed website
 * @member {String} url
 */
WebsiteSource.prototype['url'] = undefined;

/**
 * The name of the indexed website
 * @member {String} title
 */
WebsiteSource.prototype['title'] = undefined;






export default WebsiteSource;

