/**
 * CivicSage
 * CivicSage is a service that allows you to index files and websites. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import IndexWebsiteRequest from './model/IndexWebsiteRequest';
import SearchQuery from './model/SearchQuery';
import SearchResult from './model/SearchResult';
import DefaultApi from './api/DefaultApi';


/**
* CivicSage is a service that allows you to index files and websites. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CivicSage = require('index'); // See note below*.
* var xxxSvc = new CivicSage.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CivicSage.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CivicSage.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CivicSage.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The IndexWebsiteRequest model constructor.
     * @property {module:model/IndexWebsiteRequest}
     */
    IndexWebsiteRequest,

    /**
     * The SearchQuery model constructor.
     * @property {module:model/SearchQuery}
     */
    SearchQuery,

    /**
     * The SearchResult model constructor.
     * @property {module:model/SearchResult}
     */
    SearchResult,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
