/**
 * CivicSage
 * CivicSage is a service that allows you to index files and websites. 
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Feedback from './model/Feedback';
import FileSource from './model/FileSource';
import GetAllIndexedSources200Response from './model/GetAllIndexedSources200Response';
import GetMetadataKeys200Response from './model/GetMetadataKeys200Response';
import IndexFilesRequestInner from './model/IndexFilesRequestInner';
import IndexWebsiteRequest from './model/IndexWebsiteRequest';
import SearchQuery from './model/SearchQuery';
import SearchResult from './model/SearchResult';
import SummarizeEmbeddings200Response from './model/SummarizeEmbeddings200Response';
import SummarizeEmbeddingsRequest from './model/SummarizeEmbeddingsRequest';
import SystemInfo from './model/SystemInfo';
import UpdateIndexedWebsiteRequest from './model/UpdateIndexedWebsiteRequest';
import UploadFile200Response from './model/UploadFile200Response';
import WebsiteSource from './model/WebsiteSource';
import DefaultApi from './api/DefaultApi';


/**
* CivicSage is a service that allows you to index files and websites. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CivicSage = require('index'); // See note below*.
* var xxxSvc = new CivicSage.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CivicSage.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CivicSage.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CivicSage.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.5.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Feedback model constructor.
     * @property {module:model/Feedback}
     */
    Feedback,

    /**
     * The FileSource model constructor.
     * @property {module:model/FileSource}
     */
    FileSource,

    /**
     * The GetAllIndexedSources200Response model constructor.
     * @property {module:model/GetAllIndexedSources200Response}
     */
    GetAllIndexedSources200Response,

    /**
     * The GetMetadataKeys200Response model constructor.
     * @property {module:model/GetMetadataKeys200Response}
     */
    GetMetadataKeys200Response,

    /**
     * The IndexFilesRequestInner model constructor.
     * @property {module:model/IndexFilesRequestInner}
     */
    IndexFilesRequestInner,

    /**
     * The IndexWebsiteRequest model constructor.
     * @property {module:model/IndexWebsiteRequest}
     */
    IndexWebsiteRequest,

    /**
     * The SearchQuery model constructor.
     * @property {module:model/SearchQuery}
     */
    SearchQuery,

    /**
     * The SearchResult model constructor.
     * @property {module:model/SearchResult}
     */
    SearchResult,

    /**
     * The SummarizeEmbeddings200Response model constructor.
     * @property {module:model/SummarizeEmbeddings200Response}
     */
    SummarizeEmbeddings200Response,

    /**
     * The SummarizeEmbeddingsRequest model constructor.
     * @property {module:model/SummarizeEmbeddingsRequest}
     */
    SummarizeEmbeddingsRequest,

    /**
     * The SystemInfo model constructor.
     * @property {module:model/SystemInfo}
     */
    SystemInfo,

    /**
     * The UpdateIndexedWebsiteRequest model constructor.
     * @property {module:model/UpdateIndexedWebsiteRequest}
     */
    UpdateIndexedWebsiteRequest,

    /**
     * The UploadFile200Response model constructor.
     * @property {module:model/UploadFile200Response}
     */
    UploadFile200Response,

    /**
     * The WebsiteSource model constructor.
     * @property {module:model/WebsiteSource}
     */
    WebsiteSource,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
